docker_container: 'app-container'
docker_image_name: 'annadluzhinskaya/python-moscow-time'
docker_image_version: 'latest'
docker_image: "{{ docker_image_name }}:{{ docker_image_version }}"
internal_port: 8080
external_port: 8000

web_app_wipe: true
app_name: 'app_python'
app_dir: "/Users/ann_d/Desktop/{{ app_name }}"
docker_compose_path: "{{ app_dir }}/docker-compose"
docker_compose_file: 'docker-compose.yml'
docker_compose_file_path: "{{ docker_compose_path }}/{{ docker_compose_file }}"
