version: "3"

networks:
  my_network:

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "3"
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

x-healthcheck: &healthcheck
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 5s

services:
  python_application:
    image: annadluzhinskaya/python-moscow-time:latest
    container_name: python_application
    ports:
      - "8000:8080"
    networks:
      - my_network
    deploy:
        resources:
          limits:
            memory: 128m
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider --timeout=1 http://localhost:8080/healthz || exit 1"]
      <<: *healthcheck
    logging:
      <<: *logging

  sharp_application:
    image: annadluzhinskaya/pet-app:latest
    container_name: sharp_application
    ports:
      - "8088:80"
    networks:
      - my_network
    deploy:
        resources:
          limits:
            memory: 256m
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider --timeout=1 http://localhost:80/healthz || exit 1"]
      <<: *healthcheck
    logging:
      <<: *logging

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - my_network
    deploy:
        resources:
          limits:
            memory: 128m
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider --timeout=1 http://localhost:3100/ready || exit 1"]
      <<: *healthcheck
    logging:
      <<: *logging

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./config/promtail.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - my_network
    deploy:
        resources:
          limits:
            memory: 128m
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9080' || exit 1"]
      <<: *healthcheck
    logging:
      <<: *logging

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - my_network
    deploy:
        resources:
          limits:
            memory: 512m
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider --timeout=1 http://localhost:3000/api/health || exit 1"]
      <<: *healthcheck
    logging:
      <<: *logging

  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    command: '--config.file=/etc/prometheus.yaml'
    ports:
      - "9090:9090"
    networks:
      - my_network
    deploy:
      resources:
        limits:
          memory: 512m
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider --timeout=1 http://localhost:9090/-/healthy || exit 1"]
      <<: *healthcheck
    logging:
      <<: *logging
